services:
  aps:
    image: r4ulcl/wifichallengelab-aps:latest
    restart: unless-stopped
    container_name: WiFiChallengeLab-APs
    env_file: ./APs/.env
    volumes:
      - /lib/modules:/lib/modules
      - ./logsAP:/root/logs/
    network_mode: host #NETNS
    privileged: true #NETNS

  clients:
    image: r4ulcl/wifichallengelab-clients:latest
    restart: unless-stopped
    container_name: WiFiChallengeLab-Clients
    env_file: ./Clients/.env
    volumes:
      - /lib/modules:/lib/modules
      - ./logsClient:/root/logs/
    depends_on:
      - aps
    network_mode: host #NETNS
    privileged: true #NETNS
